import { useMemo, useState } from "react";
import {
  Activity, AlertTriangle, CheckCircle2, ClipboardCheck, Download,
  FileText, GitBranch, Network, Radar, ShieldCheck, Target,
} from "lucide-react";
import {
  DEMO_ATTACK_TECHNIQUES, DEMO_CAMPAIGN_EDGES, DEMO_CAMPAIGN_NODES,
  DEMO_PENDING_RULES, DEMO_SCORED_IOCS, DEMO_WEEKLY_REPORT,
  type PendingRule,
} from "./advancedDemoData";

export type IntelligenceView = "confidence" | "attack" | "campaigns" | "review" | "report";

function downloadText(filename: string, content: string, type = "text/plain") {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

const relativeTime = (value: string) => {
  const minutes = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 60_000));
  return minutes < 60 ? `${minutes}m ago` : `${Math.floor(minutes / 60)}h ago`;
};

const severityStyle = (severity: string) => severity === "critical"
  ? "bg-[#ffebe8] text-[#b5372d]" : severity === "high"
    ? "bg-[#fff3dd] text-[#a46505]" : "bg-[#edf7f1] text-[#167449]";

function Header({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="mb-5"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-[#167449]">{eyebrow}</p><h1 className="mt-1 text-[30px] font-semibold tracking-[-0.045em]">{title}</h1><p className="mt-1 text-[11px] text-[#85938b]">{description}</p></div>;
}

function MiniStat({ label, value, detail }: { label: string; value: string | number; detail: string }) {
  return <section className="rounded-[20px] border border-[#edf0ee] bg-white p-5"><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#8a9890]">{label}</p><p className="mt-3 text-[28px] font-semibold tracking-[-0.04em]">{value}</p><p className="mt-2 text-[9px] text-[#91a098]">{detail}</p></section>;
}

function ConfidenceFeed() {
  return <main className="px-1 pb-3 pt-6 sm:px-2"><Header eyebrow="Prioritized intelligence" title="Confidence-scored IOC feed" description="Corroboration, source diversity and sightings combined into an analyst-ready priority score." />
    <div className="mb-3 grid gap-3 sm:grid-cols-3"><MiniStat label="High confidence" value={DEMO_SCORED_IOCS.filter(i => i.confidence >= 80).length} detail="Score of 80 or higher"/><MiniStat label="Cross-platform" value={DEMO_SCORED_IOCS.filter(i => i.sources.length > 1).length} detail="Seen on multiple sources"/><MiniStat label="Average confidence" value={`${Math.round(DEMO_SCORED_IOCS.reduce((s, i) => s + i.confidence, 0) / DEMO_SCORED_IOCS.length)}%`} detail="Across the active feed"/></div>
    <section className="overflow-hidden rounded-[22px] border border-[#edf0ee] bg-white"><div className="grid grid-cols-[minmax(210px,1fr)_110px_150px_110px_90px] gap-3 border-b border-[#edf0ee] bg-[#f8faf9] px-5 py-3 text-[9px] font-semibold uppercase tracking-[0.12em] text-[#8a9890]"><span>Indicator</span><span>Confidence</span><span>Sources</span><span>Campaign</span><span>Last seen</span></div>{DEMO_SCORED_IOCS.map(i => <div key={i.id} className="grid grid-cols-[minmax(210px,1fr)_110px_150px_110px_90px] items-center gap-3 border-b border-[#f0f2f1] px-5 py-4 last:border-0"><div className="min-w-0"><div className="flex gap-2"><span className={`rounded-md px-2 py-1 text-[8px] font-semibold uppercase ${severityStyle(i.severity)}`}>{i.type}</span><span className={`rounded-md px-2 py-1 text-[8px] font-semibold uppercase ${severityStyle(i.severity)}`}>{i.severity}</span></div><p className="mt-2 truncate font-mono text-[10px] text-[#425149]">{i.value}</p></div><div><div className="flex items-center gap-2"><b className="text-[13px] text-[#167449]">{i.confidence}</b><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-[#e8eeeb]"><div className="h-full rounded-full bg-[#26a86b]" style={{ width: `${i.confidence}%` }}/></div></div><p className="mt-1 text-[8px] text-[#91a098]">{i.sightings} sightings</p></div><div className="flex flex-wrap gap-1">{i.sources.map(s => <span key={s} className="rounded-md bg-[#f2f5f3] px-1.5 py-1 text-[8px] text-[#65746c]">{s}</span>)}</div><span className="truncate text-[9px] font-semibold text-[#536259]">{i.campaign}</span><span className="text-[9px] text-[#93a098]">{relativeTime(i.last_seen)}</span></div>)}</section></main>;
}

function AttackHeatmap() {
  const tactics = [...new Set(DEMO_ATTACK_TECHNIQUES.map(t => t.tactic))];
  return <main className="px-1 pb-3 pt-6 sm:px-2"><Header eyebrow="MITRE ATT&CK mapping" title="ATT&CK Navigator heatmap" description="Technique coverage derived from extracted indicators and campaign context; ready for Navigator layer export." />
    <div className="mb-3 flex flex-wrap items-center justify-between gap-3 rounded-[18px] border border-[#edf0ee] bg-white p-4"><div className="flex items-center gap-2 text-[10px] text-[#65746c]"><Radar size={16} className="text-[#167449]"/> Enterprise ATT&CK · Demo layer · {DEMO_ATTACK_TECHNIQUES.length} techniques</div><button className="inline-flex items-center gap-2 rounded-xl bg-[#167449] px-4 py-2 text-[9px] font-semibold text-white"><Download size={13}/> Export Navigator JSON</button></div>
    <section className="overflow-x-auto rounded-[22px] border border-[#edf0ee] bg-white p-5"><div className="grid min-w-[900px] grid-cols-5 gap-3">{tactics.map(tactic => <div key={tactic}><p className="mb-3 rounded-xl bg-[#102f23] px-3 py-2.5 text-center text-[9px] font-semibold text-white">{tactic}</p><div className="space-y-2">{DEMO_ATTACK_TECHNIQUES.filter(t => t.tactic === tactic).map(t => <article key={t.id} className="rounded-xl border p-3" style={{ backgroundColor: `rgba(22,116,73,${0.08 + t.score / 150})`, borderColor: `rgba(22,116,73,${0.2 + t.score / 160})` }}><div className="flex justify-between gap-2"><span className="font-mono text-[9px] font-semibold">{t.id}</span><b className="text-[10px] text-[#0e5336]">{t.score}</b></div><p className="mt-2 text-[9px] font-semibold leading-4">{t.name}</p><p className="mt-2 text-[8px] text-[#536259]">{t.evidence} evidence links</p></article>)}</div></div>)}</div><div className="mt-5 flex items-center gap-3 text-[8px] text-[#87958d]"><span>Low</span>{[.12,.25,.4,.58,.76].map(v => <span key={v} className="h-3 w-8 rounded" style={{ backgroundColor: `rgba(22,116,73,${v})` }}/>) }<span>High confidence</span></div></section></main>;
}

function CampaignGraph() {
  const node = (id: string) => DEMO_CAMPAIGN_NODES.find(n => n.id === id)!;
  const colors = { campaign: "#167449", actor: "#70459a", ioc: "#c46b16", source: "#1876a8" };
  return <main className="px-1 pb-3 pt-6 sm:px-2"><Header eyebrow="Cross-platform correlation" title="Campaign graph" description="A connected view of actors, infrastructure, indicators and originating social sources."/><div className="grid gap-3 xl:grid-cols-[1fr_280px]"><section className="relative min-h-[610px] overflow-hidden rounded-[22px] border border-[#edf0ee] bg-[radial-gradient(circle_at_center,#f2f7f4_0,#fff_62%)]"><svg className="absolute inset-0 h-full w-full" aria-label="Campaign relationship graph">{DEMO_CAMPAIGN_EDGES.map((e, i) => <line key={i} x1={`${node(e.from).x}%`} y1={`${node(e.from).y}%`} x2={`${node(e.to).x}%`} y2={`${node(e.to).y}%`} stroke="#b8c9c0" strokeWidth="1.5" strokeDasharray={i > 5 ? "5 5" : undefined}/>)}</svg>{DEMO_CAMPAIGN_NODES.map(n => <div key={n.id} className="absolute -translate-x-1/2 -translate-y-1/2 text-center" style={{ left: `${n.x}%`, top: `${n.y}%` }}><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl border-4 border-white text-white shadow-lg" style={{ backgroundColor: colors[n.kind] }}>{n.kind === "campaign" ? <Target size={19}/> : n.kind === "actor" ? <ShieldCheck size={18}/> : n.kind === "ioc" ? <AlertTriangle size={17}/> : <Activity size={17}/>}</span><p className="mt-2 max-w-36 rounded-lg bg-white/90 px-2 py-1 text-[9px] font-semibold shadow-sm">{n.label}</p></div>)}</section><aside className="space-y-3"><section className="rounded-[22px] bg-[#102f23] p-5 text-white"><p className="text-[9px] uppercase tracking-[0.14em] text-white/55">Primary cluster</p><h2 className="mt-2 text-[23px] font-semibold">NightJackal</h2><p className="mt-2 text-[10px] leading-5 text-white/65">High-confidence phishing and loader activity corroborated across three collection platforms.</p><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/10 p-3"><b className="text-xl">96%</b><p className="text-[8px] text-white/55">confidence</p></div><div className="rounded-xl bg-white/10 p-3"><b className="text-xl">6</b><p className="text-[8px] text-white/55">linked objects</p></div></div></section>{Object.entries(colors).map(([kind,color]) => <div key={kind} className="flex items-center gap-3 rounded-xl border border-[#edf0ee] bg-white p-3 text-[9px] capitalize text-[#536259]"><span className="h-3 w-3 rounded-full" style={{backgroundColor:color}}/>{kind}</div>)}</aside></div></main>;
}

function ReviewQueue() {
  const [rules, setRules] = useState(DEMO_PENDING_RULES);
  const review = (id: string, approve: boolean) => setRules(current => current.filter(rule => rule.id !== id));
  return <main className="px-1 pb-3 pt-6 sm:px-2"><Header eyebrow="Human-in-the-loop validation" title="Pending-review rules" description="Approve, reject or return generated detections before SIEM and EDR deployment."/><div className="mb-3 grid gap-3 sm:grid-cols-3"><MiniStat label="Awaiting review" value={rules.length} detail="Analyst decision required"/><MiniStat label="Critical priority" value={rules.filter(r => r.severity === "critical").length} detail="Review these first"/><MiniStat label="Average IOC coverage" value={(rules.reduce((s,r)=>s+r.ioc_count,0)/Math.max(1,rules.length)).toFixed(1)} detail="Indicators per rule"/></div><section className="space-y-3">{rules.map((rule: PendingRule) => <article key={rule.id} className="flex flex-col gap-4 rounded-[20px] border border-[#edf0ee] bg-white p-5 lg:flex-row lg:items-center"><span className={`grid h-12 w-12 shrink-0 place-items-center rounded-2xl ${rule.format === "Sigma" ? "bg-[#e8f4ff] text-[#1876a8]" : "bg-[#f2ecf8] text-[#70459a]"}`}><ClipboardCheck size={19}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><span className="font-mono text-[8px] text-[#91a098]">{rule.id}</span><span className={`rounded-md px-2 py-0.5 text-[8px] font-semibold ${severityStyle(rule.severity)}`}>{rule.severity}</span><span className="rounded-md bg-[#f2f5f3] px-2 py-0.5 text-[8px] font-semibold text-[#65746c]">{rule.status}</span></div><h2 className="mt-2 text-[13px] font-semibold">{rule.title}</h2><p className="mt-1 text-[9px] text-[#87958d]">{rule.format} · {rule.target} · {rule.ioc_count} IOCs · {rule.campaign} · {relativeTime(rule.created_at)}</p></div><div className="flex gap-2"><button onClick={() => review(rule.id,false)} className="rounded-xl border border-[#e2e7e4] px-3 py-2 text-[9px] font-semibold text-[#65746c]">Request changes</button><button onClick={() => review(rule.id,true)} className="inline-flex items-center gap-1.5 rounded-xl bg-[#167449] px-3 py-2 text-[9px] font-semibold text-white"><CheckCircle2 size={12}/> Approve</button></div></article>)}{rules.length === 0 && <div className="grid min-h-64 place-items-center rounded-[22px] border border-[#dcebe3] bg-[#f3faf6] text-center"><div><CheckCircle2 className="mx-auto text-[#167449]" size={34}/><p className="mt-3 text-[13px] font-semibold">Review queue cleared</p><p className="mt-1 text-[10px] text-[#789086]">All demo rules have been processed.</p></div></div>}</section></main>;
}

function WeeklyReport() {
  const r = DEMO_WEEKLY_REPORT;
  return <main className="px-1 pb-3 pt-6 sm:px-2"><Header eyebrow="Executive intelligence" title="Latest weekly report" description="One briefing tying collection, analysis, ATT&CK mapping, campaigns and detection output together."/><article className="overflow-hidden rounded-[24px] border border-[#e5eae7] bg-white shadow-[0_20px_50px_rgba(31,52,40,0.06)]"><header className="bg-[#102f23] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-[#70d7a6]">RedTraces AI · Weekly brief</p><h2 className="mt-3 text-[27px] font-semibold">{r.title}</h2><p className="mt-2 text-[10px] text-white/55">Reporting period: {r.period} · Generated {relativeTime(r.generated_at)}</p></div><button className="inline-flex h-fit items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-[9px] font-semibold text-[#102f23]"><Download size={13}/> Download PDF</button></div></header><div className="p-6 sm:p-8"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{Object.entries(r.metrics).map(([label,value]) => <div key={label} className="rounded-xl bg-[#f5f8f6] p-3"><b className="text-[19px]">{value}</b><p className="mt-1 text-[8px] capitalize text-[#87958d]">{label.replace("_"," ")}</p></div>)}</div><section className="mt-7 rounded-[18px] border-l-4 border-[#167449] bg-[#f3faf6] p-5"><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#167449]">Executive summary</p><p className="mt-3 text-[11px] leading-6 text-[#536259]">{r.executive_summary}</p></section><div className="mt-7 grid gap-6 lg:grid-cols-2"><section><h3 className="flex items-center gap-2 text-[12px] font-semibold"><AlertTriangle size={15} className="text-[#c46b16]"/> Key findings</h3><div className="mt-3 space-y-2">{r.findings.map((f,i)=><div key={f} className="flex gap-3 rounded-xl border border-[#edf0ee] p-3"><span className="font-mono text-[9px] font-semibold text-[#167449]">0{i+1}</span><p className="text-[10px] leading-5 text-[#65746c]">{f}</p></div>)}</div></section><section><h3 className="flex items-center gap-2 text-[12px] font-semibold"><ShieldCheck size={15} className="text-[#167449]"/> Recommended actions</h3><div className="mt-3 space-y-2">{r.recommendations.map((f,i)=><div key={f} className="flex gap-3 rounded-xl border border-[#edf0ee] p-3"><CheckCircle2 size={14} className="mt-0.5 shrink-0 text-[#167449]"/><p className="text-[10px] leading-5 text-[#65746c]">{f}</p></div>)}</div></section></div><div className="mt-8 flex flex-wrap items-center gap-2 border-t border-[#edf0ee] pt-5 text-[8px] text-[#91a098]"><FileText size={12}/> Generated from collection, normalized IOC, STIX store, ATT&CK mapping, campaign correlation and rule-generation modules.</div></div></article></main>;
}

export function IntelligenceWorkspace({ view }: { view: IntelligenceView }) {
  const component = useMemo(() => ({ confidence: <ConfidenceFeed/>, attack: <AttackHeatmap/>, campaigns: <CampaignGraph/>, review: <ReviewQueue/>, report: <DownloadableWeeklyReport/> })[view], [view]);
  return component;
}

function DownloadableWeeklyReport() {
  const r = DEMO_WEEKLY_REPORT;
  return <main className="px-1 pb-3 pt-6 sm:px-2"><Header eyebrow="Executive intelligence" title="Latest weekly report" description="One briefing tying collection, analysis, ATT&CK mapping, campaigns and detection output together."/><article className="overflow-hidden rounded-[24px] border border-[#e5eae7] bg-white shadow-[0_20px_50px_rgba(31,52,40,0.06)]"><header className="bg-[#102f23] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div><p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-[#70d7a6]">RedTraces AI · Weekly brief</p><h2 className="mt-3 text-[27px] font-semibold">{r.title}</h2><p className="mt-2 text-[10px] text-white/55">Reporting period: {r.period} · Generated {relativeTime(r.generated_at)}</p></div><button onClick={() => window.print()} title="Choose Save as PDF in the print dialog" className="inline-flex h-fit items-center justify-center gap-2 rounded-xl bg-white px-4 py-2.5 text-[9px] font-semibold text-[#102f23]"><Download size={13}/> Save report as PDF</button></div></header><div className="p-6 sm:p-8"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{Object.entries(r.metrics).map(([label,value]) => <div key={label} className="rounded-xl bg-[#f5f8f6] p-3"><b className="text-[19px]">{value}</b><p className="mt-1 text-[8px] capitalize text-[#87958d]">{label.replace("_"," ")}</p></div>)}</div><section className="mt-7 rounded-[18px] border-l-4 border-[#167449] bg-[#f3faf6] p-5"><p className="text-[9px] font-semibold uppercase tracking-[0.12em] text-[#167449]">Executive summary</p><p className="mt-3 text-[11px] leading-6 text-[#536259]">{r.executive_summary}</p></section><div className="mt-7 grid gap-6 lg:grid-cols-2"><section><h3 className="flex items-center gap-2 text-[12px] font-semibold"><AlertTriangle size={15} className="text-[#c46b16]"/> Key findings</h3><div className="mt-3 space-y-2">{r.findings.map((f,i)=><div key={f} className="flex gap-3 rounded-xl border border-[#edf0ee] p-3"><span className="font-mono text-[9px] font-semibold text-[#167449]">0{i+1}</span><p className="text-[10px] leading-5 text-[#65746c]">{f}</p></div>)}</div></section><section><h3 className="flex items-center gap-2 text-[12px] font-semibold"><ShieldCheck size={15} className="text-[#167449]"/> Recommended actions</h3><div className="mt-3 space-y-2">{r.recommendations.map(f=><div key={f} className="flex gap-3 rounded-xl border border-[#edf0ee] p-3"><CheckCircle2 size={14} className="mt-0.5 shrink-0 text-[#167449]"/><p className="text-[10px] leading-5 text-[#65746c]">{f}</p></div>)}</div></section></div></div></article></main>;
}

export function ManualRuleBuilder() {
  const [format, setFormat] = useState<"Sigma" | "YARA">("Sigma");
  const [title, setTitle] = useState("Block confirmed NightJackal infrastructure");
  const [indicator, setIndicator] = useState("203.0.113.77");
  const [generated, setGenerated] = useState<Array<{ title: string; format: "Sigma" | "YARA"; content: string }>>([]);
  const build = () => {
    if (!title.trim() || !indicator.trim()) return;
    const content = format === "Sigma" ? `title: ${title}\nid: ${crypto.randomUUID()}\nstatus: experimental\nlogsource:\n  category: firewall\ndetection:\n  selection:\n    destination.ip:\n      - ${indicator}\n  condition: selection\nlevel: high\n` : `// V1 hash rule; extend with strings and byte patterns.\nrule ${title.replace(/[^A-Za-z0-9_]/g, "_")} {\n  meta:\n    description = "Generated in RedTraces AI"\n  condition:\n    hash.sha256(0, filesize) == "${indicator}"\n}\n`;
    setGenerated(current => [{ title, format, content }, ...current]);
  };
  return <section className="mb-3 rounded-[22px] border border-[#dcebe3] bg-[#f3faf6] p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-[9px] font-semibold uppercase tracking-[0.14em] text-[#167449]">Manual authoring</p><h2 className="mt-1 text-[15px] font-semibold">Create a detection rule</h2></div><span className="text-[9px] text-[#789086]">Demo builder · downloadable output</span></div><div className="mt-4 grid gap-2 lg:grid-cols-[110px_1fr_1fr_auto]"><select value={format} onChange={e => setFormat(e.target.value as "Sigma" | "YARA")} className="rounded-xl border border-[#dfe6e2] bg-white px-3 py-2.5 text-[10px]"><option>Sigma</option><option>YARA</option></select><input value={title} onChange={e => setTitle(e.target.value)} aria-label="Rule title" className="rounded-xl border border-[#dfe6e2] bg-white px-3 py-2.5 text-[10px]"/><input value={indicator} onChange={e => setIndicator(e.target.value)} aria-label="IOC value" className="rounded-xl border border-[#dfe6e2] bg-white px-3 py-2.5 font-mono text-[10px]"/><button onClick={build} className="rounded-xl bg-[#167449] px-4 py-2.5 text-[9px] font-semibold text-white">Generate rule</button></div>{generated.length > 0 && <div className="mt-4 space-y-2">{generated.map((rule,index)=><div key={`${rule.title}-${index}`} className="flex items-center gap-3 rounded-xl border border-[#e2e9e5] bg-white p-3"><FileText size={15} className="text-[#167449]"/><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-semibold">{rule.title}</p><p className="text-[8px] text-[#91a098]">{rule.format} · generated just now</p></div><button onClick={() => downloadText(`${rule.title.replace(/[^A-Za-z0-9_-]/g,"_")}.${rule.format === "Sigma" ? "yml" : "yar"}`,rule.content)} className="inline-flex items-center gap-1 rounded-lg border border-[#dfe6e2] px-3 py-2 text-[8px] font-semibold"><Download size={11}/> Download</button></div>)}</div>}</section>;
}

export function SettingsWorkspace() {
  const [compact,setCompact] = useState(() => localStorage.getItem("rt-compact") === "true");
  const [animate,setAnimate] = useState(() => localStorage.getItem("rt-animate") !== "false");
  const [refresh,setRefresh] = useState(() => localStorage.getItem("rt-refresh") || "15");
  const [saved,setSaved] = useState(false);
  const save = () => { localStorage.setItem("rt-compact",String(compact)); localStorage.setItem("rt-animate",String(animate)); localStorage.setItem("rt-refresh",refresh); setSaved(true); window.setTimeout(()=>setSaved(false),1800); };
  return <main className="px-1 pb-3 pt-6 sm:px-2"><Header eyebrow="Workspace preferences" title="Settings" description="Configure the local dashboard demonstration without changing collector credentials."/><div className="grid gap-3 xl:grid-cols-[1fr_320px]"><section className="rounded-[22px] border border-[#edf0ee] bg-white p-6"><h2 className="text-[13px] font-semibold">Display and feed</h2><label className="mt-5 flex items-center justify-between border-b border-[#edf0ee] pb-4"><span><b className="block text-[10px]">Compact signal cards</b><small className="text-[9px] text-[#91a098]">Show more intelligence rows</small></span><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)} className="h-4 w-4 accent-[#167449]"/></label><label className="flex items-center justify-between border-b border-[#edf0ee] py-4"><span><b className="block text-[10px]">Insert animations</b><small className="text-[9px] text-[#91a098]">Animate new live signals</small></span><input type="checkbox" checked={animate} onChange={e=>setAnimate(e.target.checked)} className="h-4 w-4 accent-[#167449]"/></label><label className="mt-4 block text-[9px] font-semibold text-[#65746c]">Refresh interval<select value={refresh} onChange={e=>setRefresh(e.target.value)} className="mt-2 block w-full rounded-xl border border-[#dfe6e2] bg-white px-3 py-3 text-[10px]"><option value="5">Every 5 seconds</option><option value="15">Every 15 seconds</option><option value="30">Every 30 seconds</option></select></label><button onClick={save} className="mt-5 rounded-xl bg-[#167449] px-5 py-2.5 text-[9px] font-semibold text-white">{saved ? "Preferences saved" : "Save preferences"}</button></section><aside className="rounded-[22px] bg-[#102f23] p-6 text-white"><p className="text-[9px] uppercase tracking-[0.14em] text-white/50">Environment</p><h2 className="mt-2 text-[20px] font-semibold">Demo mode active</h2><p className="mt-3 text-[10px] leading-5 text-white/60">All modules use safe synthetic data. Collector API keys are not needed for this presentation mode.</p><div className="mt-5 rounded-xl bg-white/10 p-4 font-mono text-[9px] text-white/70">VITE_DEMO_MODE=true</div></aside></div></main>;
}
